# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Servicio', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Precio', models.IntegerField()),
                ('Duracion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicios',
                'ordering': ['Nombre_Servicio'],
            },
        ),
    ]
