# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fecha_Final', models.DateTimeField()),
                ('Monto_Mora', models.DecimalField(decimal_places=2, max_digits=18)),
                ('DescripcionMora', models.CharField(max_length=500)),
                ('PagoId', models.ForeignKey(db_column='PagoId', on_delete=django.db.models.deletion.PROTECT, related_name='moras', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Mora',
                'verbose_name_plural': 'Moras',
                'db_table': 'Mora',
                'ordering': ['-Fecha_Inicio'],
            },
        ),
    ]
