# Generated by Django on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion


def migrar_mora_a_factura(apps, schema_editor):
    Mora = apps.get_model('mora', 'Mora')

    vistos = set()
    for mora in Mora.objects.select_related('PagoId', 'PagoId__FacturaId').order_by('id'):
        factura_id = mora.PagoId.FacturaId_id if mora.PagoId_id else None
        if not factura_id:
            mora.delete()
            continue

        if factura_id in vistos:
            mora.delete()
            continue

        mora.FacturaId_id = factura_id
        mora.save(update_fields=['FacturaId'])
        vistos.add(factura_id)


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_reglas_vencimiento_estados'),
        ('mora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mora',
            name='FacturaId',
            field=models.ForeignKey(db_column='FacturaId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mora_temporal', to='factura.factura'),
        ),
        migrations.RunPython(migrar_mora_a_factura, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mora',
            name='PagoId',
        ),
        migrations.AlterField(
            model_name='mora',
            name='FacturaId',
            field=models.OneToOneField(db_column='FacturaId', on_delete=django.db.models.deletion.PROTECT, related_name='mora', to='factura.factura'),
        ),
    ]
