# Generated by Django on 2026-06-14

from datetime import time

from django.db import migrations, models


def separar_fecha_hora_moras(apps, schema_editor):
    Mora = apps.get_model('mora', 'Mora')

    for mora in Mora.objects.all():
        fecha_inicio = mora.Fecha_Inicio
        fecha_final = mora.Fecha_Final

        mora.Hora_Inicio = (
            fecha_inicio.time().replace(microsecond=0)
            if fecha_inicio
            else time(0, 0)
        )
        mora.Hora_Final = (
            fecha_final.time().replace(microsecond=0)
            if fecha_final
            else time(0, 0)
        )
        mora.save(update_fields=['Hora_Inicio', 'Hora_Final'])


class Migration(migrations.Migration):

    dependencies = [
        ('mora', '0002_mora_depende_de_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='mora',
            name='Hora_Inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mora',
            name='Hora_Final',
            field=models.TimeField(null=True),
        ),
        migrations.RunPython(separar_fecha_hora_moras, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mora',
            name='Fecha_Inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mora',
            name='Fecha_Final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mora',
            name='Hora_Inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mora',
            name='Hora_Final',
            field=models.TimeField(),
        ),
        migrations.AlterModelOptions(
            name='mora',
            options={
                'ordering': ['-Fecha_Inicio', '-Hora_Inicio'],
                'verbose_name': 'Mora',
                'verbose_name_plural': 'Moras',
            },
        ),
    ]
