# Generated by Django on 2026-06-14

from django.db import migrations, models


def marcar_moras_pagadas(apps, schema_editor):
    Mora = apps.get_model('mora', 'Mora')

    for mora in Mora.objects.select_related('FacturaId').all():
        tiene_pago_confirmado = mora.FacturaId.pagos.filter(EstadoPago=True).exists()
        if mora.EstadoMora != tiene_pago_confirmado:
            mora.EstadoMora = tiene_pago_confirmado
            mora.save(update_fields=['EstadoMora'])


class Migration(migrations.Migration):

    dependencies = [
        ('mora', '0003_separar_fecha_hora_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='mora',
            name='EstadoMora',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marcar_moras_pagadas, migrations.RunPython.noop),
    ]
