# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecioVenta', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'db_table': 'Detalle_Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Emision', models.DateTimeField()),
                ('Fecha_Vencimiento', models.DateTimeField()),
                ('Monto_Total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CodigoFact', models.IntegerField(unique=True)),
                ('ContratoId', models.ForeignKey(db_column='ContratoId', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
                'ordering': ['-Fecha_Emision'],
            },
        ),
    ]
