# Generated by Django 4.2 on 2026-06-09 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='UsuarioId',
            field=models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='FacturaId',
            field=models.ForeignKey(db_column='FacturaId', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ServicioId',
            field=models.ForeignKey(db_column='ServicioId', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='servicios.servicio'),
        ),
    ]
