# Generated by Django on 2026-06-09

from django.db import migrations, models


def recalcular_facturas_existentes(apps, schema_editor):
    Factura = apps.get_model('factura', 'Factura')
    DetalleFactura = apps.get_model('factura', 'DetalleFactura')

    for factura in Factura.objects.all():
        total = 0
        detalles = DetalleFactura.objects.filter(FacturaId=factura)

        for detalle in detalles:
            total += detalle.PrecioVenta * detalle.Cantidad

        factura.Monto_Total = total
        factura.save(update_fields=['Monto_Total'])


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Monto_Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='Cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(recalcular_facturas_existentes, migrations.RunPython.noop),
    ]
