# Generated by Django on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion


ESTADOS_FACTURA = [
    (1, 'Pendiente'),
    (2, 'Pagada'),
    (3, 'Vencida'),
    (4, 'Anulada'),
    (5, 'Mora'),
]


def cargar_estados_factura(apps, schema_editor):
    EstadoFactura = apps.get_model('factura', 'EstadoFactura')

    for estado_id, estado in ESTADOS_FACTURA:
        EstadoFactura.objects.update_or_create(
            id=estado_id,
            defaults={'estado': estado},
        )


def eliminar_estados_factura(apps, schema_editor):
    EstadoFactura = apps.get_model('factura', 'EstadoFactura')
    EstadoFactura.objects.filter(id__in=[estado_id for estado_id, _ in ESTADOS_FACTURA]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_calculos_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de factura',
                'verbose_name_plural': 'Estados de factura',
                'db_table': 'estado_factura',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(cargar_estados_factura, eliminar_estados_factura),
        migrations.AddField(
            model_name='factura',
            name='EstadoId',
            field=models.ForeignKey(db_column='EstadoId', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='factura.estadofactura'),
        ),
    ]
