# Generated by Django on 2026-06-14

from datetime import time

from django.db import migrations, models


def separar_fecha_hora_facturas(apps, schema_editor):
    Factura = apps.get_model('factura', 'Factura')

    for factura in Factura.objects.all():
        fecha_emision = factura.Fecha_Emision
        fecha_vencimiento = factura.Fecha_Vencimiento

        factura.Hora_Emision = (
            fecha_emision.time().replace(microsecond=0)
            if fecha_emision
            else time(0, 0)
        )
        factura.Hora_Vencimiento = (
            fecha_vencimiento.time().replace(microsecond=0)
            if fecha_vencimiento
            else time(0, 0)
        )
        factura.save(update_fields=['Hora_Emision', 'Hora_Vencimiento'])


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_estado_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Hora_Emision',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Hora_Vencimiento',
            field=models.TimeField(null=True),
        ),
        migrations.RunPython(separar_fecha_hora_facturas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='factura',
            name='Fecha_Emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Fecha_Vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Hora_Emision',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Hora_Vencimiento',
            field=models.TimeField(),
        ),
    ]
