# Generated by Django on 2026-06-14

from datetime import time, timedelta

from django.db import migrations


HORA_FIN_DIA = time(23, 59, 0)


def aplicar_reglas_vencimiento(apps, schema_editor):
    Factura = apps.get_model('factura', 'Factura')
    EstadoFactura = apps.get_model('factura', 'EstadoFactura')

    pendiente, _ = EstadoFactura.objects.get_or_create(
        estado='Pendiente',
        defaults={'id': 1},
    )
    vencida, _ = EstadoFactura.objects.get_or_create(
        estado='Vencida',
        defaults={'id': 3},
    )

    estado_mora = EstadoFactura.objects.filter(estado__iexact='Mora').first()
    if estado_mora:
        Factura.objects.filter(EstadoId=estado_mora).update(EstadoId=vencida)
        estado_mora.delete()

    for factura in Factura.objects.select_related('ContratoId', 'ContratoId__TipoContratoId'):
        tipo = getattr(getattr(factura.ContratoId, 'TipoContratoId', None), 'Nombre', '')
        dias_plazo = 30 if tipo.strip().lower() == 'servicio mensual' else 0
        factura.Fecha_Vencimiento = factura.Fecha_Emision + timedelta(days=dias_plazo)
        factura.Hora_Vencimiento = HORA_FIN_DIA

        if not factura.EstadoId_id:
            factura.EstadoId = pendiente

        factura.save(update_fields=['Fecha_Vencimiento', 'Hora_Vencimiento', 'EstadoId'])


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_separar_fecha_hora_factura'),
    ]

    operations = [
        migrations.RunPython(aplicar_reglas_vencimiento, migrations.RunPython.noop),
    ]
