# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('IdLog', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tabla', models.CharField(max_length=128)),
                ('Accion', models.CharField(max_length=20)),
                ('ClavePrincipal', models.CharField(blank=True, max_length=128, null=True)),
                ('Usuario', models.CharField(default='', max_length=128)),
                ('Host', models.CharField(default='', max_length=128)),
                ('Fecha', models.DateTimeField()),
                ('Detalle', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'db_table': 'LogAuditoria',
                'ordering': ['-Fecha'],
            },
        ),
    ]
