# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inc', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('EstadoContrato', models.BooleanField(default=True)),
                ('Descripcion', models.CharField(max_length=250)),
                ('ClienteId', models.ForeignKey(db_column='ClienteId', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contratos',
                'ordering': ['-Fecha_Inc'],
            },
        ),
    ]
