# Generated by Django 5.2 on 2026-06-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=80, unique=True)),
                ('Descripcion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contrato',
                'db_table': 'TipoContrato',
                'ordering': ['Nombre'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='TipoContratoId',
            field=models.ForeignKey(blank=True, db_column='TipoContratoId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.tipocontrato'),
        ),
    ]
