# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Envio', models.DateTimeField()),
                ('Mensaje', models.CharField(max_length=250)),
                ('EstadoNotificacion', models.BooleanField(default=False)),
                ('ClienteId', models.ForeignKey(db_column='ClienteId', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificaciones',
                'ordering': ['-Fecha_Envio'],
            },
        ),
    ]
