# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Pago', models.DateTimeField()),
                ('Monto_Pagado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('EstadoPago', models.BooleanField(default=False)),
                ('MetodoPago', models.BooleanField(default=False)),
                ('NumeroRecibo', models.IntegerField(unique=True)),
                ('FacturaId', models.ForeignKey(db_column='FacturaId', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='factura.factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
                'ordering': ['-Fecha_Pago'],
            },
        ),
    ]
