# Generated by Django 5.2 on 2025-10-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre1', models.CharField(max_length=30)),
                ('Nombre2', models.CharField(max_length=30)),
                ('Apellido1', models.CharField(max_length=30)),
                ('Apellido2', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Celular', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
