# Generated by Django 4.2 on 2026-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreClt', models.CharField(max_length=50)),
                ('ApellidoClt', models.CharField(max_length=50)),
                ('TelefonoClt', models.IntegerField()),
                ('DireccionClt', models.CharField(max_length=100)),
                ('FechaRegistroClt', models.DateTimeField()),
                ('CorreoClt', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['NombreClt', 'ApellidoClt'],
            },
        ),
    ]
