# Generated by Django on 2026-06-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamentos_nombre_unique'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='DepartamentoId',
            field=models.ForeignKey(
                db_column='DepartamentoId',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='clientes',
                to='departamentos.departamentos',
            ),
        ),
    ]
