# Generated by Django on 2026-06-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_departamentoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='NombreClt',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ApellidoClt',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='TelefonoClt',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='DireccionClt',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='FechaRegistroClt',
            new_name='FechaRegistro',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CorreoClt',
            new_name='Correo',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={
                'ordering': ['Nombre', 'Apellido'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
