# Generated by Django on 2026-06-09

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_cliente_fields_without_clt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message='El telefono debe tener 8 digitos o el formato +505 seguido de 8 digitos.',
                        regex='^(\\+505)?\\d{8}$',
                    ),
                ],
            ),
        ),
    ]
