# Generated by Django on 2026-06-09

from django.db import migrations, models
from django.db.models import Q
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_fecharegistro_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Cedula',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='La cedula debe tener formato nicaraguense, por ejemplo 001-010190-0001A.',
                        regex='^\\d{3}-?\\d{6}-?\\d{4}[A-Za-z]$',
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(
                condition=Q(('Cedula__isnull', False)),
                fields=('Cedula',),
                name='uq_clientes_cedula_not_null',
            ),
        ),
    ]
