# Generated by Django on 2026-06-09

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        message='El telefono solo puede contener digitos, espacios, guiones, parentesis y un signo + inicial.',
                        regex='^\\+?[0-9\\s\\-\\(\\)]+$',
                    ),
                ],
            ),
        ),
    ]
