# Generated by Django 5.2 on 2026-06-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_telefono_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
