# Generated by Django 5.2 on 2026-06-13 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_horaregistro_fecha_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='El telefono debe tener formato nicaraguense: +505 0000 0000.', regex='^\\+505 [0-9]{4} [0-9]{4}$')]),
        ),
    ]
