"""
Django settings for SoftFactur project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from apps.catalogos.setting_apps import CATALOGOS_SETTING_APPS
from apps.seguridad.setting_apps import SEGURIDAD_SETTING_APPS
from apps.transaccion.setting_apps import TRANSACCION_SETTING_APPS


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_^g1s7$h$liggji3v79#^%ro15s86tvn7a5%2_g117a0hycjug'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
]

LOCAL_APPS = SEGURIDAD_SETTING_APPS + CATALOGOS_SETTING_APPS + TRANSACCION_SETTING_APPS

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'SoftFactur.cors.DevCorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SoftFactur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SoftFactur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.sqlite3',
#      'NAME': BASE_DIR / 'db.sqlite3',
#   }
#}

DATABASES = {
    'default': {
        'ENGINE': 'SoftFactur.db.backends.mssql_no_mars',  # Backend mssql-django sin MARS para este SQL Server local
        'NAME': 'BDsofactur',  # Nombre de la base de datos
        'HOST': 'localhost',  # SQL Server Express por TCP
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',  # Driver ODBC instalado
            'trusted_connection': 'yes',  # Habilita la autenticación de Windows
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no',  # Desarrollo local con SQL Server Express
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Managua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.user'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

SOFTFACTUR_EMAIL = 'loganblandon044@gmail.com'

EMAIL_BACKEND = os.environ.get(
    'SOFTFACTUR_EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('SOFTFACTUR_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('SOFTFACTUR_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('SOFTFACTUR_EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('SOFTFACTUR_EMAIL_USER', SOFTFACTUR_EMAIL)
EMAIL_HOST_PASSWORD = os.environ.get('SOFTFACTUR_EMAIL_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('SOFTFACTUR_EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = f'SoftFactur <{EMAIL_HOST_USER}>'
SERVER_EMAIL = EMAIL_HOST_USER
LOGIN_URL = '/frontend/Softlutionic/login.html'
