# Generated by Django on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
