# Generated by Django on 2026-06-09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_clienteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Nombre',
            new_name='PrimerNombre',
        ),
        migrations.AddField(
            model_name='user',
            name='SegundoNombre',
            field=models.CharField(default='Pendiente', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 6, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='HoraRegistro',
            field=models.TimeField(auto_now_add=True, default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='PrimerNombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['PrimerNombre', 'SegundoNombre', 'email'],
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
